In [106]:
import numpy as np
import random
import os

In [107]:
binary_string="100100001111100100110111110011101010110100"

In [124]:
# n_nodes range from 4 to 22
f=[]

In [125]:
def make_graph():
    n=random.randint(4,22)
    adj={}
    for i in range(1,n+1):
        q=random.randint(1,n)
        adj[(i,0)]=q
        q=random.randint(1,n)
        adj[(i,1)]=q
    x=np.zeros((n,2))
    start = random.randint(1,n)
    r=(int)((n+2)/3)
    l=random.sample(range(1, n+1), r)
    x[start-1][0]=0
    x[start-1][1]=1
    for i in l:
        if i==start:
            x[i-1][0]=1
            x[i-1][1]=0
            continue
        x[i-1][0]=1
        x[i-1][1]=1
    # x is ready
    a=np.zeros((n,n))
    for i in range(1,n+1):
        a[i-1][adj[(i,0)]-1]=1
        a[i-1][adj[(i,1)]-1]=1
    #a is ready
    current=start
    check=[]
    check.append(current)
    for w in binary_string:
        if w=='0':
            r=0
        else:
            r=1
        current=adj[(current,r)]
        check.append(current)
        
    e=np.zeros((n,n,2))
    for i in range(1,n+1):
        e[i-1][adj[(i,0)]-1][0]=1
        e[i-1][adj[(i,0)]-1][1]=0
        e[i-1][adj[(i,1)]-1][0]=0
        e[i-1][adj[(i,1)]-1][1]=1
            
    ok=0
    for zz in check:
        if zz in l:
            ok=1
            break
    if ok==0:
        dd=random.choice(check)
        x[dd-1][0]=1
        x[dd-1][1]=1
    y=[]
    y.append(start)
    current=start
    for w in binary_string:
        if w=='0':
            r=0
        else:
            r=1
        current=adj[(current,r)]
        y.append(current)
    if current in l:
        y.append(1)
    else:
        y.append(0)
    y=np.array(y)
    return x,a,e,y

In [133]:
x,a,e,y=make_graph()

In [134]:
len(binary_string)

42

In [143]:
x

array([[0., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.]])

In [144]:
a

array([[0., 1., 1., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 1., 1., 0.]])

In [145]:
y

array([1, 3, 4, 3, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4,
       2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 3, 4, 2, 1, 3, 3, 4, 2, 1, 2, 1])

In [146]:
e

array([[[0., 0.],
        [1., 0.],
        [0., 1.],
        [0., 0.]],

       [[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 1.],
        [1., 0.]],

       [[0., 0.],
        [0., 1.],
        [1., 0.],
        [0., 0.]]])

In [142]:
a.shape[0]

4

In [147]:
path="/Users/harshit/Projects/YALE-RESEARCH-WORK/dataset_automata"

In [148]:
count=0
for i in range(0,1000):
    x,a,e,y=make_graph()
    if y[-1]==1:
        count=count+1

print(count)

372


In [149]:
for i in range(0,11000):        
    filename = os.path.join(path, f'graph_{i}')
    x,a,e,y=make_graph()
    np.savez(filename, x=x, a=a, e=e, y=y)

In [150]:
path="/Users/harshit/Projects/YALE-RESEARCH-WORK/dataset_automata_test"

In [151]:
for i in range(1000):
    filename = os.path.join(path, f'graph_{i}')
    x,a,e,y=make_graph()
    np.savez(filename, x=x, a=a, e=e, y=y)