In [74]:
import numpy as np
import random
import os

In [75]:
binary_string="001110110101010101111000001010101110100110001001100100111100100001011010000010001101111010100001011011110001010101011111100100110111000011010001111000011001000000100000100"

In [76]:
# n_nodes range from 4 to 42
f=[]

In [101]:
def make_graph():
    n=random.randint(4,42)
    adj={}
    for i in range(1,n+1):
        q=random.randint(1,n)
        adj[(i,0)]=q
        q=random.randint(1,n)
        adj[(i,1)]=q
    x=np.zeros((n,2))
    start = random.randint(1,n)
    r=(int)((n+2)/3)
    l=random.sample(range(1, n+1), r)
    x[start-1][0]=0
    x[start-1][1]=1
    for i in l:
        if i==start:
            x[i-1][0]=1
            x[i-1][1]=0
            continue
        x[i-1][0]=1
        x[i-1][1]=1
    # x is ready
    a=np.zeros((n,n))
    for i in range(1,n+1):
        a[i-1][adj[(i,0)]-1]=1
        a[i-1][adj[(i,1)]-1]=2
    #a is ready
    current=start
    check=[]
    check.append(current)
    for w in binary_string:
        if w=='0':
            r=0
        else:
            r=1
        current=adj[(current,r)]
        check.append(current)
    ok=0
    for zz in check:
        if zz in l:
            ok=1
            break
    if ok==0:
        dd=random.choice(check)
        x[dd-1][0]=1
        x[dd-1][1]=1
    y=[]
    y.append(start)
    current=start
    for w in binary_string:
        if w=='0':
            r=0
        else:
            r=1
        current=adj[(current,r)]
        y.append(current)
    if current in l:
        y.append(1)
    else:
        y.append(0)
    y=np.array(y)
    return x,a,y

In [102]:
x,a,y=make_graph()

In [103]:
len(binary_string)

171

In [104]:
x

array([[0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.]])

In [105]:
a

array([[0., 0., 2., 0., 0.],
       [0., 0., 0., 1., 2.],
       [0., 2., 0., 1., 0.],
       [0., 0., 2., 0., 1.],
       [0., 0., 0., 2., 0.]])

In [95]:
y

array([ 2, 19, 28, 19, 17,  9, 20, 14,  2, 19, 17, 30,  6,  3, 21,  7, 17,
       30,  6,  1, 22, 15, 19, 28, 26, 25, 13, 17, 30,  6,  3, 21,  7, 17,
        9, 30, 21,  9, 20, 10, 21,  9, 20, 10, 17,  9, 20, 10, 21,  9, 20,
       10, 21,  7, 18, 20, 14,  2, 25, 13,  9, 30, 21,  7, 18, 20, 14, 22,
       15,  2, 19, 17, 30, 21,  7, 18, 20, 14, 22, 15, 19, 17,  9, 20, 14,
        2, 25, 17, 30,  6,  3, 21,  7, 18, 20, 10, 21,  7, 17,  9, 20, 14,
        2, 25, 17, 30, 21,  7, 17, 30,  6,  3, 21,  7, 17, 30,  6,  1, 22,
       15,  2, 25, 13,  9, 30, 21,  7, 17,  9, 20, 14,  2, 25, 13,  9, 20,
       10, 21,  9, 20, 14, 22, 15, 19, 17,  9, 30,  6,  3, 14, 22, 15,  2,
       25, 13,  9, 30, 21,  7, 18, 20, 10, 17,  9, 20, 10, 17, 30, 21,  9,
       20, 10,  1])

In [96]:
path="/Users/harshit/Projects/YALE-RESEARCH-WORK/dataset_automata"

In [100]:
count=0
for i in range(0,1000):
    x,a,y=make_graph()
    if y[-1]==1:
        count=count+1

print(count)

208


In [72]:
for i in range(0,1000):        
    filename = os.path.join(path, f'graph_{i}')
    x,a,y=make_graph()
    np.savez(filename, x=x, a=a, y=y)