In [35]:
import numpy as np
import random
import os

In [36]:
binary_string="100100001111100100110111110011101010110100"

In [37]:
# n_nodes range from 4 to 22
f=[]
len(binary_string)

42

In [38]:
def make_graph():
    n=random.randint(4,22)
    adj={}
    for i in range(1,n+1):
        q=random.randint(1,n)
        adj[(i,0)]=q
        q=random.randint(1,n)
        adj[(i,1)]=q
    x=np.zeros((n,2))
    start = random.randint(1,n)
    #r=random.sample(range(1,(int)((n+1)/2)+1),1)
    r=(int)(((n+2)/3)+1)
    r=random.randrange(1,r)
    l=random.sample(range(1, n+1), r)
    x[start-1][0]=0
    x[start-1][1]=1
    for i in l:
        if i==start:
            x[i-1][0]=1
            x[i-1][1]=0
            continue
        x[i-1][0]=1
        x[i-1][1]=1
    # x is ready
    a=np.zeros((n,n))
    for i in range(1,n+1):
        a[i-1][adj[(i,0)]-1]=1
        a[i-1][adj[(i,1)]-1]=1
    #a is ready
    current=start
    check=[]
    check.append(current)
    for w in binary_string:
        if w=='0':
            r=0
        else:
            r=1
        current=adj[(current,r)]
        check.append(current)
        
    e=np.zeros((n,n,2))
    for i in range(1,n+1):
        e[i-1][adj[(i,0)]-1][0]=1
        e[i-1][adj[(i,0)]-1][1]=0
        e[i-1][adj[(i,1)]-1][0]=0
        e[i-1][adj[(i,1)]-1][1]=1
            
    ok=0
    for zz in check:
        if zz in l:
            ok=1
            break
    if ok==0:
        dd=random.choice(check)
        x[dd-1][0]=1
        x[dd-1][1]=1
    y=[]
    y.append(start)
    current=start
    for w in binary_string:
        if w=='0':
            r=0
        else:
            r=1
        current=adj[(current,r)]
        y.append(current)
    if current in l:
        y.append(100)
    else:
        y.append(0)
    y=np.array(y)
    return x,a,e,y

In [39]:
x,a,e,y=make_graph()

In [40]:
len(binary_string)

42

In [41]:
x

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [0., 0.]])

In [27]:
a

array([[0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [28]:
y

array([1, 9, 7, 1, 9, 7, 1, 2, 7, 9, 1, 9, 1, 9, 7, 1, 9, 7, 1, 9, 1, 2,
       3, 8, 1, 9, 1, 2, 7, 9, 1, 9, 7, 9, 7, 9, 7, 9, 1, 2, 3, 7, 1, 0])

In [29]:
e

array([[[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 1.]],

       [[0., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 1.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 1.]],

       [[0., 0.],
        [1., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 1.],
        [0., 0.]],

       [[0., 0.],
        [1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[1., 0.]

In [30]:
a.shape[0]

9

In [31]:
path="/Users/harshit/Projects/YALE-RESEARCH-WORK/dataset_automata"

In [33]:
count=0
for i in range(0,1000):
    x,a,e,y=make_graph()
    if y[-1]==100:
        count=count+1

print(count)

248


In [34]:
for i in range(0,11000):        
    filename = os.path.join(path, f'graph_{i}')
    x,a,e,y=make_graph()
    np.savez(filename, x=x, a=a, e=e, y=y)

In [68]:
path="/Users/harshit/Projects/YALE-RESEARCH-WORK/dataset_automata_test"

In [69]:
for i in range(1000):
    filename = os.path.join(path, f'graph_{i}')
    x,a,e,y=make_graph()
    np.savez(filename, x=x, a=a, e=e, y=y)